# Generated by Django 2.1.1 on 2018-09-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=55)),
                ('productdesc', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=45)),
                ('teamname_eng', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryid',
        ),
        migrations.AlterModelTable(
            name='productcat',
            table='productcat',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Productcat',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='products',
            name='categoryid',
            field=models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.DO_NOTHING, to='store.Productcat'),
        ),
        migrations.AddField(
            model_name='products',
            name='teamid',
            field=models.ForeignKey(db_column='teamid', on_delete=django.db.models.deletion.DO_NOTHING, to='store.Teams'),
        ),
    ]
