# Generated by Django 2.1.1 on 2018-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('playerid', models.AutoField(primary_key=True, serialize=False)),
                ('playername', models.CharField(max_length=45)),
                ('avg', models.DecimalField(decimal_places=0, max_digits=3)),
                ('h', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('era', models.DecimalField(decimal_places=0, max_digits=3)),
                ('w', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('so', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
