# Generated by Django 2.1.1 on 2019-05-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20181001_0857'),
        ('player', '0003_auto_20180930_2208'),
    ]

    operations = [
    ]
