# Generated by Django 2.1.1 on 2019-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'actmember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idlocation', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
